# Generated by Django 3.2.18 on 2023-03-08 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_controller_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='unit_weight',
            field=models.FloatField(default=0),
        ),
    ]
