# Generated by Django 3.2.18 on 2023-05-16 11:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_controller_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='price',
            new_name='unit_price',
        ),
        migrations.AlterField(
            model_name='ingredientscalculation',
            name='quantity',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.DeleteModel(
            name='IntermediateIngredientRecipe',
        ),
    ]
