# Generated by Django 3.2.18 on 2023-04-13 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('stock_controller_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredientquantity',
            options={'ordering': ['ingredient_name']},
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['recipe_name']},
        ),
        migrations.RenameField(
            model_name='ingredientquantity',
            old_name='name',
            new_name='ingredient_name',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='name',
            new_name='recipe_name',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='customuser_set', related_query_name='customuser', to='auth.Group', verbose_name='groups'),
        ),
    ]
