# Generated by Django 3.2.18 on 2023-05-16 18:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_controller_app', '0002_auto_20230516_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientquantity',
            name='quantity',
            field=models.PositiveIntegerField(default=500, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
