# Generated by Django 3.2.18 on 2023-03-25 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_controller_app', '0002_auto_20230325_1145'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ingredientsQuantity',
            new_name='Quantity',
        ),
    ]
