# Generated by Django 3.2.18 on 2023-03-09 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_controller_app', '0002_ingredient_unit_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='slug',
            field=models.SlugField(default=models.CharField(max_length=50, unique=True), max_length=200, unique=True),
        ),
    ]
