# Generated by Django 3.2.18 on 2023-04-23 12:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_controller_app', '0002_auto_20230413_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='tubs',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='price',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='type',
            field=models.IntegerField(choices=[(0, 'Solid'), (1, 'Liquid'), (3, 'Non-Edibles')], default=0),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='unit_weight',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='units',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='ingredientquantity',
            name='quantity',
            field=models.PositiveIntegerField(default=500, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterUniqueTogether(
            name='ingredientquantity',
            unique_together={('ingredient_name', 'quantity')},
        ),
    ]
