# Generated by Django 3.2.18 on 2023-04-26 10:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock_controller_app', '0003_auto_20230423_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='price',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.CreateModel(
            name='ingredientPriceSum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prices', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock_controller_app.ingredient')),
            ],
        ),
    ]
