# Generated by Django 3.2.18 on 2023-03-25 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_controller_app', '0003_rename_ingredientsquantity_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='liquidsQuantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=500)),
                ('name', models.ManyToManyField(limit_choices_to={'type': 1}, related_name='liquid_recipes', to='stock_controller_app.Ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='solidsQuantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=500)),
                ('name', models.ManyToManyField(limit_choices_to={'type': 0}, related_name='solid_recipes', to='stock_controller_app.Ingredient')),
            ],
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='ingredient',
        ),
        migrations.DeleteModel(
            name='Quantity',
        ),
        migrations.AddField(
            model_name='recipe',
            name='liquid_ingredient',
            field=models.ManyToManyField(to='stock_controller_app.liquidsQuantity'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='solid_ingredient',
            field=models.ManyToManyField(to='stock_controller_app.solidsQuantity'),
        ),
    ]
