# Generated by Django 3.2.18 on 2023-03-10 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_controller_app', '0003_ingredient_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
