# Generated by Django 3.2.18 on 2023-03-25 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock_controller_app', '0004_auto_20230325_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liquidsquantity',
            name='name',
        ),
        migrations.AddField(
            model_name='liquidsquantity',
            name='name',
            field=models.ForeignKey(default=3, limit_choices_to={'type': 1}, on_delete=django.db.models.deletion.CASCADE, related_name='liquid_recipes', to='stock_controller_app.ingredient'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='solidsquantity',
            name='name',
        ),
        migrations.AddField(
            model_name='solidsquantity',
            name='name',
            field=models.ForeignKey(default=1, limit_choices_to={'type': 0}, on_delete=django.db.models.deletion.CASCADE, related_name='solid_recipes', to='stock_controller_app.ingredient'),
            preserve_default=False,
        ),
    ]
