# Generated by Django 3.2.18 on 2023-04-26 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_controller_app', '0004_auto_20230426_1015'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ingredientPriceSum',
        ),
    ]
