# Generated by Django 3.2.18 on 2023-03-11 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_controller_app', '0005_alter_ingredient_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='type',
            field=models.IntegerField(choices=[(0, 'solid'), (1, 'liquid')], default=0),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
