# Generated by Django 3.2.18 on 2023-03-26 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock_controller_app', '0005_auto_20230325_1513'),
    ]

    operations = [
        migrations.CreateModel(
            name='ingredientQuantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=500)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock_controller_app.ingredient')),
            ],
        ),
        migrations.RemoveField(
            model_name='solidsquantity',
            name='name',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='liquid_ingredient',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='solid_ingredient',
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredient',
            field=models.ManyToManyField(to='stock_controller_app.Ingredient'),
        ),
        migrations.DeleteModel(
            name='liquidsQuantity',
        ),
        migrations.DeleteModel(
            name='solidsQuantity',
        ),
    ]
