# Generated by Django 3.2.18 on 2023-04-27 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_controller_app', '0006_intermediaterecipeingredient'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IntermediateRecipeIngredient',
        ),
    ]
