# Generated by Django 3.2.18 on 2023-03-13 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_controller_app', '0006_auto_20230311_0103'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='supplier',
            field=models.CharField(default='VILA', max_length=20),
        ),
    ]
