# Generated by Django 3.2.18 on 2023-03-26 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_controller_app', '0006_auto_20230326_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredient',
            field=models.ManyToManyField(to='stock_controller_app.ingredientQuantity'),
        ),
    ]
