# Generated by Django 3.2.18 on 2023-03-28 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock_controller_app', '0007_alter_recipe_ingredient'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredientquantity',
            options={'ordering': ['name']},
        ),
        migrations.CreateModel(
            name='IngredientsCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock_controller_app.recipe')),
            ],
        ),
    ]
