# Generated by Django 3.2.18 on 2023-03-20 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_controller_app', '0007_ingredient_supplier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='slug',
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='type',
            field=models.IntegerField(choices=[(0, 'Solid'), (1, 'Liquid')], default=0),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='units',
            field=models.IntegerField(default=1),
        ),
    ]
