# Generated by Django 3.2.18 on 2023-05-02 11:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_controller_app', '0007_delete_intermediaterecipeingredient'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientscalculation',
            name='ingredient',
            field=models.ManyToManyField(to='stock_controller_app.ingredientQuantity'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='price',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='ingredientquantity',
            name='quantity',
            field=models.FloatField(default=500, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
