# Generated by Django 3.2.18 on 2023-03-21 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock_controller_app', '0008_auto_20230320_0027'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('solid_ingredients', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock_controller_app.ingredient')),
            ],
        ),
    ]
