# Generated by Django 3.2.18 on 2023-05-02 17:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_controller_app', '0008_auto_20230502_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientquantity',
            name='quantity',
            field=models.PositiveIntegerField(default=500),
        ),
        migrations.AlterField(
            model_name='ingredientscalculation',
            name='quantity',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
