# Generated by Django 3.2.18 on 2023-05-02 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_controller_app', '0009_auto_20230502_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientscalculation',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
