# Generated by Django 3.2.18 on 2023-03-21 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_controller_app', '0010_auto_20230321_0042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='solid_ingredients',
        ),
        migrations.AddField(
            model_name='recipe',
            name='solids',
            field=models.ManyToManyField(limit_choices_to={'type': 0}, to='stock_controller_app.Ingredient'),
        ),
    ]
