# Generated by Django 3.2.18 on 2023-03-21 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_controller_app', '0011_auto_20230321_0054'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='add_ons',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='recipe',
            name='intermediate_procedures',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='recipe',
            name='liquids',
            field=models.ManyToManyField(limit_choices_to={'type': 1}, related_name='liquid_recipes', to='stock_controller_app.Ingredient'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='solids',
            field=models.ManyToManyField(limit_choices_to={'type': 0}, related_name='solid_recipes', to='stock_controller_app.Ingredient'),
        ),
    ]
