# Generated by Django 3.2.18 on 2023-03-23 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_controller_app', '0012_auto_20230321_0102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='image',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='add_ons',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='intermediate_procedures',
        ),
        migrations.AddField(
            model_name='recipe',
            name='notes',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='unit_weight',
            field=models.IntegerField(default=0),
        ),
    ]
